spring:
  main:
    banner-mode: OFF
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgre
  jpa:
    show-sql: false
    mapping-resources:
    - queries/CategoriSql.xml
    - queries/ProductSql.xml
    
    hibernate:
      ddl-auto: none